using ChatAI.Application.Interfaces;
using ChatAI.Application.Services;
using Microsoft.Extensions.Logging;
using Microsoft.SemanticKernel;
using System.ComponentModel;

namespace ChatAI.Application.Plugins;

/// <summary>
/// Semantic Kernel plugin for sending emails to administrators
/// Allows AI to notify administrators about important issues or requests
/// </summary>
public class EmailPlugin
{
    private readonly IEmailService _emailService;
    private readonly ChatContext _chatContext;
    private readonly ILogger<EmailPlugin> _logger;

    public EmailPlugin(
        IEmailService emailService,
        ChatContext chatContext,
        ILogger<EmailPlugin> logger)
    {
        _emailService = emailService ?? throw new ArgumentNullException(nameof(emailService));
        _chatContext = chatContext ?? throw new ArgumentNullException(nameof(chatContext));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <summary>
    /// Send an email notification to the administrator/responsible person
    /// Use this when users request to contact support, report issues, or need human assistance
    /// </summary>
    /// <param name="subject">Email subject (keep it concise and descriptive)</param>
    /// <param name="message">Detailed message explaining the user's request or issue</param>
    /// <returns>Confirmation message</returns>
    [KernelFunction("send_admin_email")]
    [Description("Send an email to the administrator or responsible person. Use this when users want to contact support, report problems, request features, or need human assistance.")]
    public async Task<string> SendAdminEmailAsync(
        [Description("Email subject - brief description of the issue or request")] string subject,
        [Description("Detailed message body explaining what the user needs")] string message)
    {
        try
        {
            _logger.LogInformation("🔧 [{Context}] TOOL CALLED: send_admin_email | Subject: {Subject}", 
                _chatContext.GetContextInfo(), subject);

            if (string.IsNullOrWhiteSpace(subject))
            {
                return "❌ Cannot send email: Subject is required.";
            }

            if (string.IsNullOrWhiteSpace(message))
            {
                return "❌ Cannot send email: Message content is required.";
            }

            // Add context that this was sent by AI on behalf of a user
            var enrichedMessage = $@"
            This email was automatically generated by the AI assistant on behalf of a user.

            ---
            SUBJECT: {subject}

            MESSAGE:
            {message}

            ---
            Sent via Chatify AI Assistant
            Timestamp: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC
            ";

            var success = await _emailService.SendToAdminAsync(
                subject: $"[Chatify AI] {subject}",
                message: enrichedMessage,
                isHtml: false);

            if (success)
            {
                _logger.LogInformation("✅ [{Context}] TOOL SUCCESS: Email sent to admin", 
                    _chatContext.GetContextInfo());
                return "✅ Your message has been sent to the administrator. They will review it and get back to you soon.";
            }
            else
            {
                _logger.LogWarning("⚠️ [{Context}] TOOL FAILED: Failed to send email to admin", 
                    _chatContext.GetContextInfo());
                return "⚠️ I attempted to send your message, but there was an issue with the email service. Please try contacting support directly.";
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "❌ [{Context}] TOOL ERROR: SendAdminEmailAsync failed", 
                _chatContext.GetContextInfo());
            return "❌ An error occurred while trying to send your message. Please try again later or contact support directly.";
        }
    }

    /// <summary>
    /// Send a feature request or suggestion to the administrator
    /// </summary>
    /// <param name="featureDescription">Description of the requested feature or suggestion</param>
    /// <returns>Confirmation message</returns>
    [KernelFunction("send_feature_request")]
    [Description("Send a feature request or suggestion to the administrator. Use when users suggest improvements or new features.")]
    public async Task<string> SendFeatureRequestAsync(
        [Description("Detailed description of the feature request or suggestion")] string featureDescription)
    {
        _logger.LogInformation("🔧 [{Context}] TOOL CALLED: send_feature_request", 
            _chatContext.GetContextInfo());

        if (string.IsNullOrWhiteSpace(featureDescription))
        {
            return "❌ Please provide details about the feature you'd like to suggest.";
        }

        var message = $@"
FEATURE REQUEST from user via AI Assistant:

{featureDescription}

---
Submitted: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC
";

        var success = await _emailService.SendToAdminAsync(
            subject: "[Chatify AI] Feature Request",
            message: message,
            isHtml: false);

        if (success)
        {
            _logger.LogInformation("✅ [{Context}] TOOL SUCCESS: Feature request sent", 
                _chatContext.GetContextInfo());
            return "✅ Thank you for your suggestion! I've forwarded it to the team for review.";
        }
        else
        {
            _logger.LogWarning("⚠️ [{Context}] TOOL FAILED: Failed to send feature request", 
                _chatContext.GetContextInfo());
            return "⚠️ I couldn't submit your feature request at the moment. Please try again later.";
        }
    }

    /// <summary>
    /// Report a bug or technical issue to the administrator
    /// </summary>
    /// <param name="issueDescription">Description of the bug or technical issue</param>
    /// <returns>Confirmation message</returns>
    [KernelFunction("report_bug")]
    [Description("Report a bug or technical issue to the administrator. Use when users report errors, crashes, or unexpected behavior.")]
    public async Task<string> ReportBugAsync(
        [Description("Detailed description of the bug or issue, including steps to reproduce if possible")] string issueDescription)
    {
        _logger.LogInformation("🔧 [{Context}] TOOL CALLED: report_bug", 
            _chatContext.GetContextInfo());

        if (string.IsNullOrWhiteSpace(issueDescription))
        {
            return "❌ Please describe the issue you're experiencing.";
        }

        var message = $@"
BUG REPORT from user via AI Assistant:

ISSUE DESCRIPTION:
{issueDescription}

---
Reported: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC
";

        var success = await _emailService.SendToAdminAsync(
            subject: "[Chatify AI] Bug Report",
            message: message,
            isHtml: false);

        if (success)
        {
            _logger.LogInformation("✅ [{Context}] TOOL SUCCESS: Bug report sent", 
                _chatContext.GetContextInfo());
            return "✅ Thank you for reporting this issue! The technical team has been notified and will investigate.";
        }
        else
        {
            _logger.LogWarning("⚠️ [{Context}] TOOL FAILED: Failed to send bug report", 
                _chatContext.GetContextInfo());
            return "⚠️ I couldn't submit your bug report at the moment. Please try contacting support directly.";
        }
    }
}
